# Generated by Django 4.2.6 on 2023-10-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.CharField(max_length=255, null=True)),
                ('device_name', models.CharField(max_length=255, null=True)),
                ('extra', models.JSONField(null=True)),
                ('is_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_pin', models.IntegerField()),
                ('is_on', models.BooleanField(default=False)),
                ('relay_name', models.CharField(max_length=255, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relays', to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='RelayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('is_on', models.BooleanField(default=True)),
                ('relays', models.ManyToManyField(to='device.relay')),
            ],
        ),
    ]
