# Generated by Django 4.2.6 on 2023-10-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
